spring.application.name=workout-tracker-web-app

spring.datasource.url=jdbc:postgresql://workout-tracker.cfamssswohxm.us-east-2.rds.amazonaws.com:5432/workout-tracker
spring.datasource.username=majl
spring.datasource.password=${DB_PASSWORD}